### ISSUE TITLE
NEVER MIND, I NEED TO UPDATE MY DOCKER IMAGE

### ISSUE THREAD

**Issue by theschles** [cp2004/OctoPrint-CameraStreamer-Control#4]
NEVER MIND, I NEED TO UPDATE MY DOCKER IMAGE

**Comment by cp2004** [comment]
Indeed, the error message says that 'octoprint-camerastreamer-control' **requires** Python `<4, >=3.9` - so minimum is 3.9. 3.8.17 is not in that range so the install was rejected.
