### ISSUE TITLE
Doesn't work with go2rtc webrtc streams

### ISSUE THREAD

**Issue by puterboy** [cp2004/OctoPrint-CameraStreamer-Control#7]
The plugin doesn't seem to be able to handle mp4 webrtc streams generated by go2rtc streamer.

The webrtc url I have is of form:
```
http://mypi/api/stream.mp4?src=picam_h264
```
The stream plays just fine in my browser or in apps like mplayer and vlc.
But it fails to display in Octoprint-CameraStreamer-Control (where I selected 'WebRTC' as the Preferred Video Mode)

Any suggestions on troubleshooting this and making it work?

**Comment by cp2004** [comment]
That is because this plugin is "camera streamer control". It is designed for & only works with camera streamer, not go2rtc.

A plugin for fully supporting go2rtc would be useful, but in the meantime use the iframe webcam plugin.

**Comment by jneilliii** [comment]
I've started working on a go2rtc specific plugin: <https://github.com/jneilliii/OctoPrint-go2rtc>. Still earlier stages, but it allows for adding streams to the config and viewing multiple streams within OctoPrint. There may be bugs....

**Comment by puterboy** [comment]
That's great to hear!!!
I have hacked go2rtc to work with Obico as well as with Octoprint and it has been working mostly stable for the past year. Though sometimes it loses one of my cameras and I need to restart.

I really like the simplicity and power of go2rtc.

Will your plugin allow for multiple cameras?
I currently use both a native PiCam3 as well as a USB nozzle cam that I run through go2rtc.

Happy to help test your plugin when you are ready for it

**Comment by jneilliii** [comment]
It's very finicky right now, because the configuration has to get synched, and I noticed I missed a couple of things in the default settings that prevent it from working really proper yet. But yes, it supports multiple cameras...

![Image](https://github.com/user-attachments/assets/4e54dfdb-6ac4-4a6d-8859-0bfa810f733e)
